chore: fix apply premature tactic
team-zomsa/aplib.net pull request #19
Opened 2024-03-17 23:06 UTC by SilasPeters

2024-03-18 11:41 UTC, joachimdekker commented on Aplib.Core/Intent/Tactics/FirstOfTactic.cs
> +        public override List<PrimitiveTactic> GetFirstEnabledTactics()
Dit zou dan eigenlijk `GetAction` moeten worden. Maar ik dacht dat @Tboefijn dit zou fixen in een PR vandaag.

2024-03-18 11:42 UTC, joachimdekker submitted a review, later dismissed
LGTM!

2024-03-18 22:50 UTC, JensSteenmetz requested changes
Fixed Tactic can be pulled now.

2024-03-20 16:02 UTC, JensSteenmetz requested changes

2024-03-20 16:02 UTC, JensSteenmetz commented on Aplib.Core/Desire/Goals/Goal.cs
> +        public delegate Heuristics HeuristicFunction(BelieveSet believeSet);
```suggestion
        public delegate Heuristics HeuristicFunction(Beliefset beliefset);
```

2024-03-20 16:02 UTC, JensSteenmetz commented on Aplib.Core/Desire/Goals/Goal.cs
> +        public virtual Heuristics CurrentHeuristics(BelieveSet believeSet)
```suggestion
        public virtual Heuristics CurrentHeuristics(Beliefset beliefset)
```

2024-03-20 16:02 UTC, JensSteenmetz commented on Aplib.Core/Desire/Goals/Goal.cs
> +            => _currentHeuristics ??= _heuristicFunction.Invoke(believeSet);
```suggestion
            => _currentHeuristics ??= _heuristicFunction.Invoke(beliefset);
```

2024-03-20 16:12 UTC, JensSteenmetz approved these changes, later dismissed
LNWALWM (let's not wait any longer with merging)

2024-03-20 17:58 UTC, QuakeEye requested changes

2024-03-20 17:58 UTC, QuakeEye commented on Aplib.Core/Desire/Goals/Goal.cs
> +        /// <seealso cref="Goal.IsCompleted"/>
```suggestion
        /// <seealso cref="IsCompleted"/>
```

This is possible right? Since it is in the same class?

2024-03-20 18:22 UTC, QuakeEye approved these changes
OBNHAHLEDDOMTDGMDVECA (ik ben naar huis aan het lopen en doe dit op mijn telefoon dus geen moeite doen voor een coole afkorting)

2024-03-20 18:28 UTC, joachimdekker approved these changes
LGTM (a few nitpicks, but we'll sort them out in a more in-scope PR)

2024-03-20 18:30 UTC, merged