chore: add pull request template
team-zomsa/aplib.net pull request #26
Opened 2024-03-28 15:20 UTC by QuakeEye

## Describe your changes
This pull request adds a pull request template to ensure everything is done for each pull request that is required by our own standards.

## How to test your changes
You can not, until creating a new pull request.

## Checklist
- [X] Set the proper pull request name
- [X] Merged main into your branch

2024-03-29 11:45 UTC, joachimdekker requested changes

2024-03-29 11:45 UTC, joachimdekker commented on .github/pull_request_template.md
Kan je de headers niet beter maken van:

# Description
Propose a new change here

# Testability
How to test it...

Ik vind dat beschrijvender, want als ik het nu lees is het voor iemand die de PR gaat lezen nogal gek.

2024-03-29 11:49 UTC, QuakeEye commented on .github/pull_request_template.md
Something like this?

2024-03-29 11:50 UTC, joachimdekker approved these changes
LGTM

2024-03-31 12:38 UTC, JensSteenmetz requested changes

2024-03-31 12:38 UTC, JensSteenmetz commented on Aplib.Core/Belief/IBeliefSet.cs
> +        void UpdateBeliefs();
Undo these changes, as they are already made in 'feat: add MemoryBelief' and they don't really fit in this PR

2024-03-31 16:12 UTC, JensSteenmetz approved these changes

2024-03-31 16:13 UTC, merged