Chore: update .editorconfig
team-zomsa/aplib.net pull request #28
Opened 2024-04-01 09:54 UTC by SSelinn

## Description

This PR makes sure all fields are formatted like this: _doSomething

## Testability

If you open up a class and declare some variable: string Name, it should suggest to do _name.

## Checklist
- [x] Set the proper pull request name
- [x] Merged main into your branch

2024-04-01 15:33 UTC, JensSteenmetz requested changes
I think it should be like this?

2024-04-01 15:33 UTC, JensSteenmetz commented on .editorconfig
> +dotnet_naming_symbols.underscore_fields.applicable_kinds = field
```suggestion
dotnet_naming_symbols.underscore_fields.applicable_kinds = field, property
```

2024-04-01 15:33 UTC, JensSteenmetz commented on .editorconfig
> +dotnet_naming_symbols.underscore_fields.applicable_accessibilities = public, internal, private, protected, protected_internal, private_protected
```suggestion
dotnet_naming_symbols.underscore_fields.applicable_accessibilities = internal, private, protected, protected_internal, private_protected
```

2024-04-01 15:33 UTC, JensSteenmetz commented on .editorconfig
> +dotnet_naming_rule.fields_should_be_camel_case.severity = suggestion
```suggestion
dotnet_naming_rule.fields_should_be_camel_case.severity = warning
```

2024-04-01 15:40 UTC, JensSteenmetz requested changes
Actually, we might need to discuss this tomorrow, as there are some more issues that require some decisions regarding style.

2024-04-01 15:59 UTC, QuakeEye submitted a review, later dismissed

2024-04-02 08:21 UTC, Tboefijn submitted a review, later dismissed

2024-04-02 11:48 UTC, joachimdekker commented
Due to already implementing it in another PR, this PR does not have anything to add. Sorry. Thus, I am closing the PR.

2024-04-02 11:48 UTC, closed without merging