Add Sonarcloud
team-zomsa/aplib.net pull request #3
Opened 2024-02-12 20:54 UTC by joachimdekker

This PR proposes to add Sonarcloud to the build pipeline. I have no idea how GitHub Actions work, so I just pasted the pipeline provided by Sonarcloud and added the dotnet commands. 

@QuakeEye, please review it 🙏

2024-02-13 14:34 UTC, SilasPeters requested changes

2024-02-13 14:34 UTC, SilasPeters commented on .github/workflows/pr-build.yml
Perhaps some more explanation of why we need certain tasks?

2024-02-13 14:49 UTC, SilasPeters submitted a review, later dismissed

2024-02-13 15:26 UTC, SSelinn submitted a review, later dismissed
:D

2024-02-13 15:26 UTC, SSelinn commented on Aplib.Core/Main.cs
> +    public class SonarTest
Change class name to used format. Same as filename. :D

2024-02-13 15:26 UTC, SSelinn commented on Aplib.Core/Main.cs
> +            }
Why did you not use a for-loop? Any reason to use a while-loop?

2024-02-13 15:26 UTC, SSelinn commented on Aplib.Core/Main.cs
> +            Console.WriteLine("i is 1");
Isn't "i" a variable? Are you checking if i == 1 or are you stating it?

2024-02-13 15:26 UTC, SSelinn commented on Aplib.Tests/Aplib.Tests.csproj
> +    <TargetFramework>net8.0</TargetFramework>
Was this not something else or was it 8?

2024-02-13 15:26 UTC, SSelinn commented on Aplib.Tests/SonarTest.cs
> +public class SonarTest
Name format o.o

2024-02-13 15:40 UTC, joachimdekker commented on Aplib.Tests/Aplib.Tests.csproj
> +    <TargetFramework>net8.0</TargetFramework>
The testing project can be in .NET 8, as .NET 8 can import .NET standard 2.1 libraries and test them.

2024-02-13 15:48 UTC, joachimdekker commented on Aplib.Tests/SonarTest.cs
> +public class SonarTest
What do you mean? Also, what do you propose?

2024-02-13 15:55 UTC, SilasPeters submitted a review, later dismissed
LGTM!

2024-02-13 16:11 UTC, QuakeEye requested changes

2024-02-13 16:11 UTC, QuakeEye commented on .github/workflows/pr-build.yml
> +      - name: Set up JDK 17
Would maybe help to specify in the name that this is installed for sonarcloud as mentioned previously

2024-02-13 16:11 UTC, QuakeEye commented on .github/workflows/pr-build.yml
> +          distribution: 'zulu' # Alternative distribution options are available.
I do not think we will change this, the comment can probably be removed

2024-02-13 16:11 UTC, QuakeEye commented on .github/workflows/pr-build.yml
> +          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
This is a github thing, I don't think specifying the fetch depth is even necessary at all, as we just want to retrieve everything in this pull request

2024-02-13 16:42 UTC, joachimdekker commented on .github/workflows/pr-build.yml
> +      - name: Set up JDK 17
Isn't that a bit redundant?

2024-02-19 09:18 UTC, QuakeEye requested changes

2024-02-19 09:18 UTC, QuakeEye commented on .github/workflows/pr-build.yml
> +
```suggestion
```

🤨

2024-02-19 09:19 UTC, QuakeEye commented on Aplib.Tests/SonarTest.cs
> +public class SonarTest
This was due to the class name not being the same as the filename which had been solved, marking as resolved was alright.

2024-02-19 09:33 UTC, QuakeEye approved these changes
lgtm!

2024-02-19 09:37 UTC, SilasPeters approved these changes

2024-02-19 09:41 UTC, merged