feat(intent)!: Remove guards from actions.
team-zomsa/aplib.net pull request #46
Opened 2024-04-29 09:46 UTC by joachimdekker

## Description

This PR proposes to remove the guards from action and only use tactics.

## Checklist
- [x] Set the proper pull request name
- [x] Merged main into your branch

2024-04-29 17:40 UTC, Tboefijn approved these changes
LGTM!

2024-05-01 09:17 UTC, JensSteenmetz requested changes
Great work, I commented on some details

2024-05-01 09:17 UTC, JensSteenmetz commented on Aplib.Core/Intent/Actions/QueryAction.cs
> +            // Query the environment for the guarded item
Nit
```suggestion
            // Query the environment for the guarded item.
```

2024-05-01 09:17 UTC, JensSteenmetz commented on Aplib.Core/Intent/Actions/QueryAction.cs
> +            // Only return true if the guard is not null
Nit
```suggestion
            // Only return true if the guard is not null.
```

2024-05-01 09:17 UTC, JensSteenmetz commented on Aplib.Core/Intent/Actions/QueryAction.cs
> +            _storedGuardResult = _query(beliefSet);
```suggestion
            _storedQueryResult = _query(beliefSet);
```

2024-05-01 09:17 UTC, JensSteenmetz commented on Aplib.Core/Intent/Actions/QueryAction.cs
> +        /// <param name="query">The guard of the action.</param>
There are more comments that need to be addressed.
```suggestion
        /// <param name="query">The query of the action.</param>
```

2024-05-01 09:17 UTC, JensSteenmetz commented on Aplib.Core/Intent/Tactics/PrimitiveTactic.cs
> +            : base((beliefset) => guard(beliefset) && queryAction.Query(beliefset))
Nit
```suggestion
            : base(beliefSet => guard(beliefSet) && queryAction.Query(beliefSet), metadata)
```

2024-05-01 09:17 UTC, JensSteenmetz commented on Aplib.Core/Intent/Tactics/PrimitiveTactic.cs
> +        }
Nit
```suggestion
        =>  _action = queryAction;
```

2024-05-04 12:00 UTC, JensSteenmetz requested changes
Almost ;)

2024-05-04 12:00 UTC, JensSteenmetz commented on Aplib.Core/Intent/Actions/QueryAction.cs
> +using System;
Could you remove using System? It sometimes creates issues with our Action class vs the System.Action delegate.

2024-05-04 12:00 UTC, JensSteenmetz commented on Aplib.Core/Intent/Actions/QueryAction.cs
> +        public override void Execute(TBeliefSet beliefSet) => _effect(beliefSet, arg2: _storedQueryResult!);
```suggestion
        public override void Execute(TBeliefSet beliefSet) => _effect(beliefSet, _storedQueryResult!);
```

2024-05-04 12:29 UTC, JensSteenmetz approved these changes
LGTM!!!

2024-05-04 13:06 UTC, Tboefijn approved these changes
LGTM!

2024-05-04 13:27 UTC, merged