feat!: Restructure folders
team-zomsa/aplib.net pull request #53
Opened 2024-05-13 09:21 UTC by joachimdekker

## Description

This PR proposes to change the folder structure of aplib. It puts GoalStructure in its own folder, and creates a seperate namespace for agent.

BREAKING CHANGE: Because agent has a seperate namespace, this PR introduces a breaking change.

Closes AP-117.

## Checklist
- [x] Set the proper pull request name
- [x] Merged main into your branch

2024-05-15 12:12 UTC, SilasPeters requested changes

2024-05-15 12:12 UTC, SilasPeters commented on Aplib.Core/Desire/Goals/Goal.cs
> +    /// or do the testing.
grrrrr fix this :(((((((((((

2024-05-15 13:35 UTC, joachimdekker commented on Aplib.Core/Desire/Goals/Goal.cs
> +    /// or do the testing.
Rider won't let me :(

2024-05-16 06:27 UTC, SilasPeters approved these changes, later dismissed
You did not give any formal proofs. However, I wouldn't even check them if you did.

2024-05-16 12:25 UTC, QuakeEye commented on Aplib.Core/Desire/Goals/Goal.cs
> +    /// or do the testing.
common Rider L

2024-05-19 17:01 UTC, JensSteenmetz reviewed
Could you also introduce DesireSet, Belief.Belief and Belief.BeliefSet namespaces?

2024-05-19 17:01 UTC, JensSteenmetz commented on Aplib.Tests/Desire/GoalStructureTests.cs
> +using System;
Nit: could this using statement be removed? I would like to prevent using System namespace in aplib code, since the System.Action delegate clashes with Aplib.Core.Intent.Actions.Action. Even though Aplib.Core.Intent.Actions is not used in this script currently, it might be used later.

2024-05-19 17:01 UTC, JensSteenmetz commented on Aplib.Core/Desire/Goals/Goal.cs
Could this folder/namespace be renamed to Goal? To be consistent with the GoalStructure namespace? Same comment on Aplib.Core.Intent.Actions

2024-05-19 17:02 UTC, JensSteenmetz requested changes
Left a Comment instead of Request changes by accident.

2024-05-20 11:04 UTC, JensSteenmetz commented
To formally prove the correctness of our new folder structure, we introduce a formalized set-theoretic approach. Let's define our folder structure as a set $F$ and introduce a function $\phi$ that maps elements of $F$ to their respective responsibilities within the system.

**Axiom 1: Modularity (M)**
A folder structure $F$ is said to be modular if for every element $f \in F$, there exists a unique responsibility $r$ such that $\phi(f) = r$. This implies a one-to-one correspondence between folders and responsibilities.

**Axiom 2: Scalability (S)**
A folder structure $F$ is scalable if for any non-empty subset $G \subseteq F$, there exists an element $g \notin F$ such that $F \cup \{g\}$ is also a folder structure satisfying Axiom 1.

**Theorem: The folder structure $F$ is effective if it satisfies both Modularity (M) and Scalability (S).**

**Proof:**

Let $F = \{ Core, Agent, Belief, BeliefSet, Desire, GoalStructure, Goal, DesireSet, Intent, Action, Tactic, Collections \}$.

**Step 1: Verify Modularity**
Define $\phi: F \rightarrow R$ where $R$ is the set of responsibilities. For instance, $\phi(Agent)$ could be 'Agent Operations', $\phi(Belief)$ could be 'Belief Management', and so on.

Since each folder in $F$ has a distinct responsibility, and no two folders share the same responsibility, $\phi$ is injective, thus satisfying Modularity (M).

**Step 2: Verify Scalability**
Consider a subset $G \subseteq F$, say $G = \{ Belief, BeliefSet \}$. If we want to add a new belief $b$, we can do so by creating a new element $g \notin F$, such that $g = b$ and $\phi(g) = 'New Belief'$.

Since adding $g$ to $F$ does not require changing the existing structure and $\phi$ remains injective, $F$ satisfies Scalability (S).

By demonstrating that $F$ satisfies both Modularity (M) and Scalability (S), we conclude that the folder structure is effective according to our theorem.

2024-05-20 11:39 UTC, joachimdekker commented on Aplib.Core/Desire/Goals/Goal.cs
I don't agree. It houses multiple `Goals` just like the `System.Collections`. I will change the `GoalStructure` folder to `GoalStructures`.

2024-05-20 11:42 UTC, joachimdekker commented on Aplib.Tests/Desire/GoalStructureTests.cs
> +using System;
This is the test script. Is that really necessary?

2024-05-20 11:43 UTC, SilasPeters requested changes
The Aplib.Tests project should be renamed to Aplib.Core.Tests, for every project needs its own tests project

2024-05-20 11:45 UTC, JensSteenmetz commented on Aplib.Core/Desire/Goals/Goal.cs
That's also fine

2024-05-20 11:52 UTC, JensSteenmetz commented on Aplib.Tests/Desire/GoalStructureTests.cs
> +using System;
It is not giving issues right now, but it's sort of personal preference. I don't like to have imports that could potentially cause issues down the line. But not necessary, hence the nit. So you can leave it if you disagree.

2024-05-20 11:56 UTC, JensSteenmetz requested changes
One small thing regarding our conventions, lgtm otherwise

2024-05-20 11:56 UTC, JensSteenmetz commented on Aplib.Core/Agents/BdiAgent.cs
> +
Read-only should be above non-read-only public fields and properties

2024-05-20 13:03 UTC, JensSteenmetz approved these changes
LGTMMMM

2024-05-20 13:08 UTC, SilasPeters approved these changes

2024-05-20 13:09 UTC, merged